spring:
  application:
    name: has-zk-app-webflux
  cloud:
    zookeeper:
      discovery:
        root: /zk-service
        connect-string: localhost:2181
        metadata:
                # management.context-path: /foo
                # health.path: /ping
                 user.name: zy
                 user.password: zy
server:
  port: 8386
management:
  endpoints:
    web:
      #base-path: "/actuator"
      exposure:
        include: "*"